CREATE TABLE "knowledge_base_grants" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "knowledge_base_grants_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"knowledge_base_id" text NOT NULL,
	"grantee_type" varchar(20) NOT NULL,
	"grantee_user_id" text,
	"grantee_role_id" integer,
	"permission" varchar(20) DEFAULT 'read' NOT NULL,
	"accessed_at" timestamp with time zone DEFAULT now() NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "knowledge_bases" ALTER COLUMN "type" SET DATA TYPE varchar(20);--> statement-breakpoint
ALTER TABLE "knowledge_bases" ALTER COLUMN "type" SET DEFAULT 'personal';--> statement-breakpoint
ALTER TABLE "knowledge_bases" ADD COLUMN "enabled" boolean DEFAULT true NOT NULL;--> statement-breakpoint
ALTER TABLE "knowledge_base_grants" ADD CONSTRAINT "knowledge_base_grants_knowledge_base_id_knowledge_bases_id_fk" FOREIGN KEY ("knowledge_base_id") REFERENCES "public"."knowledge_bases"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "knowledge_base_grants" ADD CONSTRAINT "knowledge_base_grants_grantee_user_id_users_id_fk" FOREIGN KEY ("grantee_user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "knowledge_base_grants" ADD CONSTRAINT "knowledge_base_grants_grantee_role_id_rbac_roles_id_fk" FOREIGN KEY ("grantee_role_id") REFERENCES "public"."rbac_roles"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "knowledge_base_grants_grantee_user_unique" ON "knowledge_base_grants" USING btree ("knowledge_base_id","grantee_user_id");--> statement-breakpoint
CREATE UNIQUE INDEX "knowledge_base_grants_grantee_role_unique" ON "knowledge_base_grants" USING btree ("knowledge_base_id","grantee_role_id");--> statement-breakpoint
CREATE INDEX "knowledge_bases_user_type_enabled_idx" ON "knowledge_bases" USING btree ("user_id","type","enabled");
