CREATE TABLE "agents_grants" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "agents_grants_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"agent_id" text NOT NULL,
	"grantee_type" varchar(20) NOT NULL,
	"grantee_user_id" text,
	"grantee_role_id" integer,
	"accessed_at" timestamp with time zone DEFAULT now() NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "agents" ALTER COLUMN "enabled" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "agents_grants" ADD CONSTRAINT "agents_grants_agent_id_agents_id_fk" FOREIGN KEY ("agent_id") REFERENCES "public"."agents"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "agents_grants" ADD CONSTRAINT "agents_grants_grantee_user_id_users_id_fk" FOREIGN KEY ("grantee_user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "agents_grants" ADD CONSTRAINT "agents_grants_grantee_role_id_rbac_roles_id_fk" FOREIGN KEY ("grantee_role_id") REFERENCES "public"."rbac_roles"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "agents_grants_grantee_user_unique" ON "agents_grants" USING btree ("agent_id","grantee_user_id");--> statement-breakpoint
CREATE UNIQUE INDEX "agents_grants_grantee_role_unique" ON "agents_grants" USING btree ("agent_id","grantee_role_id");
