-- Custom SQL migration file for customization and announcements tables --

-- Create customization table (single-row table, id always equals 1)
CREATE TABLE IF NOT EXISTS "customization" (
  "id" integer PRIMARY KEY DEFAULT 1,
  "base" jsonb,
  "welcome" jsonb,
  "default_agent" jsonb,
  "updated_by" text,
  "updated_at" timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT "customization_id_check" CHECK ("id" = 1)
);

-- Create announcements table
CREATE TABLE IF NOT EXISTS "announcements" (
  "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "title" text NOT NULL,
  "content" text NOT NULL,
  "effective_start_at" timestamp with time zone NOT NULL,
  "effective_end_at" timestamp with time zone NOT NULL,
  "created_by" text NOT NULL,
  "updated_by" text NOT NULL,
  "created_at" timestamp with time zone NOT NULL DEFAULT now(),
  "updated_at" timestamp with time zone NOT NULL DEFAULT now()
);

-- Create indexes for announcements table
CREATE INDEX IF NOT EXISTS "announcements_effective_time_idx" ON "announcements" ("effective_start_at", "effective_end_at");
CREATE INDEX IF NOT EXISTS "announcements_created_at_idx" ON "announcements" ("created_at");

-- Insert initial row for customization table (id=1)
INSERT INTO "customization" ("id", "updated_at")
VALUES (1, now())
ON CONFLICT ("id") DO NOTHING;
