-- Create agents_grants table for Agent authorization control
CREATE TABLE IF NOT EXISTS "agents_grants" (
  "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "agent_id" text NOT NULL,
  "grantee_type" varchar(20) NOT NULL,
  "grantee_user_id" text,
  "grantee_role_id" text,
  "accessed_at" timestamp with time zone DEFAULT now() NOT NULL,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL
);

--> statement-breakpoint

-- Create indexes for agents_grants table
CREATE UNIQUE INDEX IF NOT EXISTS "agents_grants_grantee_user_unique" ON "agents_grants" USING btree ("agent_id", "grantee_user_id");
CREATE UNIQUE INDEX IF NOT EXISTS "agents_grants_grantee_role_unique" ON "agents_grants" USING btree ("agent_id", "grantee_role_id");
CREATE INDEX IF NOT EXISTS "agents_grants_agent_id_idx" ON "agents_grants" USING btree ("agent_id");
CREATE INDEX IF NOT EXISTS "agents_grants_grantee_role_id_idx" ON "agents_grants" USING btree ("grantee_role_id");

--> statement-breakpoint

-- Add foreign key constraints
DO $$ BEGIN
  ALTER TABLE "agents_grants" ADD CONSTRAINT "agents_grants_agent_id_agents_id_fk"
    FOREIGN KEY ("agent_id") REFERENCES "public"."agents"("id")
    ON DELETE cascade ON UPDATE no action;
EXCEPTION
  WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
  ALTER TABLE "agents_grants" ADD CONSTRAINT "agents_grants_grantee_user_id_users_id_fk"
    FOREIGN KEY ("grantee_user_id") REFERENCES "public"."users"("id")
    ON DELETE cascade ON UPDATE no action;
EXCEPTION
  WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
  ALTER TABLE "agents_grants" ADD CONSTRAINT "agents_grants_grantee_role_id_rbac_roles_id_fk"
    FOREIGN KEY ("grantee_role_id") REFERENCES "public"."rbac_roles"("id")
    ON DELETE cascade ON UPDATE no action;
EXCEPTION
  WHEN duplicate_object THEN null;
END $$;
