CREATE TABLE "logs" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "logs_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"code" text NOT NULL,
	"type" varchar(20) NOT NULL,
	"belong" varchar(20),
	"user_id" text NOT NULL,
	"user_agent" text,
	"ip" text,
	"input" jsonb,
	"output" jsonb,
	"duration" integer,
	"success" boolean,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
